# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

env:
 global:
 - R_BUILD_ARGS="--no-manual --keep-empty-dirs --no-resave-data"
 - R_CHECK_ARGS="--no-vignettes --timings --no-manual"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - wget https://www.dropbox.com/s/m1ps15zcn5fn4ad/rmf_cytoscape.tar.gz
  - tar -xzf rmf_cytoscape.tar.gz
  - "export DISPLAY=:99.0"
  - Xvfb :99 -ac &
  - Cytoscape_v2.8.3/cytoscape.sh &

install:
  - ./travis-tool.sh aptget_install r-cran-xml
  - ./travis-tool.sh bioc_install Biobase BiocGenerics AnnotationDbi GSEABase Category GOstats annotate graph RCytoscape GO.db KEGG.db estrogen org.Hs.eg.db hgu95av2.db limma affy genefilter
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
