# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

env:
 global:
 - R_BUILD_ARGS="--no-manual --keep-empty-dirs --no-resave-data"
 - R_CHECK_ARGS="--no-vignettes --timings --no-manual"
 - secure: "dHknlaJtXultVqPvFRce3BdBa6gxgFNvaqN1k9rd0PAVSThOhKxPjQ9IYiINgYujtTCJXWFPKyyG76OoTlWfRsbV+XDieWu9TqQk96yTc8wi4p93RffsYJypg7qhy8lGc2rDqwge0f48v6IB0g6pIsHjWz6pq7nW+OBSUFvBGV4="

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - chmod 755 ./.push_gh_pages.sh
  - ./travis-tool.sh bootstrap
  - pwd
  - ls

install:
  - ./travis-tool.sh aptget_install r-cran-xml
  - ./travis-tool.sh bioc_install Biobase BiocGenerics AnnotationDbi GSEABase Category GOstats annotate graph RCy3 GO.db KEGG.db estrogen org.Hs.eg.db hgu95av2.db limma affy genefilter
  - ./travis-tool.sh install_deps

script:
  - ./travis-tool.sh run_tests

after_success:
  - ./.push_gh_pages.sh

after_failure:
  - ./travis-tool.sh dump_logs


notifications:
  email:
    on_success: change
    on_failure: change
